apiVersion: ecs.aws.upbound.io/v1beta1
kind: TaskDefinition
metadata:
  labels:
    testing.upbound.io/example-name: sample-app-task
  name: sample-app-task
spec:
  forProvider:
    executionRoleArn: arn:aws:iam::011882408883:role/ecsTaskExecutionRole
    containerDefinitions: |
      [
        {
          "name": "sample-app-container",
          "image": "nginxdemos/hello:latest",
          "cpu": 0,
          "memoryReservation": 2048,
          "essential": true,
          "PortMappings": [
            {
            "hostPort": 8081,
            "ContainerPort" : 8081,
            "Protocol" : "tcp" 
            }
          ]
        }
      ]
    cpu: '1024'
    family: sample-app-task
    memory: '2048'
    networkMode: awsvpc
    region: us-east-1
    requiresCompatibilities: 
      - FARGATE
    taskRoleArn: arn:aws:iam::011882408883:role/ecs-to-rds
